title: Sibo Wang
logo: /assets/img/profile.jpg
show_downloads: false
description: "**Work:** sibo DOT wang AT epfl DOT ch<br>**Personal:** wangchensibo AT gmail DOT com"
google_analytics: G-SD641HJRFZ
github:
  is_project_page: false
  is_user_page: false
theme: jekyll-theme-minimal
