title: Sibo Wang-Chen
logo: /assets/img/profile.jpg
show_downloads: false
description: "[Contact info](https://people.epfl.ch/sibo.wang?lang=en)"
google_analytics: G-SD641HJRFZ
github:
  is_project_page: false
  is_user_page: false
theme: jekyll-theme-minimal
