title: Sibo Wang-Chen
logo: /assets/img/profile.jpg
show_downloads: false
description: "sibo.wang [at] epfl [dot] ch"
google_analytics: G-SD641HJRFZ
github:
  is_project_page: false
  is_user_page: false
theme: jekyll-theme-minimal
