title: Sibo Wang
logo: /assets/img/profile.jpg
show_downloads: false
description: "<b>Work:</b> sibo DOT wang AT epfl DOT ch<br><b>Personal:</b> wangchensibo AT gmail DOT com"
google_analytics: G-SD641HJRFZ
github:
  is_project_page: false
  is_user_page: false
theme: jekyll-theme-minimal
