title: Sibo Wang-Chen
logo: /assets/img/profile.jpg
show_downloads: false
description: "<a href="https://people.epfl.ch/sibo.wang?lang=en">Contact info</a>"
google_analytics: G-SD641HJRFZ
github:
  is_project_page: false
  is_user_page: false
theme: jekyll-theme-minimal
